dist: xenial
branches:
  only:
    - master
language: csharp
solution: eForm-MachineArea-dotnet/eForm-MachineArea-dotnet.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - cd eForm-MachineArea-dotnet
  - dotnet restore
  - dotnet build eForm-MachineArea-dotnet.sln
  - dotnet test -v n eForm-MachineArea-dotnet.Integration.Tests/eForm-MachineArea-dotnet.Integration.Tests.csproj
  - dotnet build eForm-MachineArea-dotnet.sln -c Release
  - revision=${TRAVIS_JOB_ID:=1}
  - echo $revision
  - revision=${printf "%4d" $revision}
  - echo $revision
