dist: xenial
branches:
  only:
    - master
language: csharp
solution: eForm-MachineArea-dotnet.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build eForm-MachineArea-dotnet.sln
  - dotnet test -v n eForm-MachineArea-dotnet.Integration.Tests/eForm-MachineArea-dotnet.Integration.Tests.csproj
